### ISSUE TITLE
Need a cookie banner to be GDPR compliant

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/janus-idp.github.io#29]
## Goal
Provide a cookie banner to be GDBR compliant

**Comment by serenamarie125** [comment]
@rtaniwa can we get this prioritized asap?  

Sounds like we need a cookie banner on janus-idp.io to be GDBR compliant

**Comment by christophe-f** [comment]
I would probably use something like https://www.cookieconsent.com/ to generate the banner.
or https://brainsum.github.io/cookieconsent/

**Comment by schultzp2020** [comment]
Currently the only cookies we use are for segment (analytics) and cannot be turned off. The data that is sent to segment follows GDPRs guidance on gathering analytics because the data is sufficiently difficult to re identify the users. Therefore, the dialog only needs to say we use cookies for anonymous analytics and it cannot be turned off.
